export const inputs = [
  {
    name: "propetyTaxIPTU",
    label: "IPTU",
    type: "date",
    placeholder: "",
  },
  {
    name: "propertyTaxIPTUValue",
    label: "Valor pago do IPTU",
    type: "price",
    placeholder: "",
    description: "",
  },
  {
    name: "statusPropertyTaxIPTU",
    label: "Status",
    type: "selectStatus",
    placeholder: "",
    description: "Status",
  },
  {
    name: "propertyTaxIPTUPerson",
    label: "IPTU pago por:",
    type: "selectFinancePerson",
    placeholder: "",
    description: "Status",
  },
  {
    name: "rent",
    label: "Aluguel",
    type: "date",
    placeholder: "",
  },
  {
    name: "rentValue",
    label: "Valor pago do aluguel",
    type: "price",
    placeholder: "",
    description: "",
  },
  {
    name: "statusRent",
    label: "Status",
    type: "selectStatus",
    placeholder: "",
    description: "Status",
  },
  {
    name: "rentPerson",
    label: "Aluguel pago por:",
    type: "selectFinancePerson",
    placeholder: "",
    description: "Status",
  },
  {
    name: "condominium",
    label: "Condominio",
    type: "date",
    placeholder: "",
  },
  {
    name: "condominiumValue",
    label: "Valor pago do condomínio",
    type: "price",
    placeholder: "",
    description: "",
  },
  {
    name: "statusCondominium",
    label: "Status",
    type: "selectStatus",
    placeholder: "",
    description: "Status",
  },
  {
    name: "condominiumPerson",
    label: "Condomínio pago por:",
    type: "selectFinancePerson",
    placeholder: "",
    description: "Status",
  },
  {
    name: "sabesp",
    label: "Água",
    type: "date",
    placeholder: "",
    description: "",
  },
  {
    name: "sabespValue",
    label: "Valor pago da Água",
    type: "price",
    placeholder: "",
    description: "",
  },
  {
    name: "statusSabesp",
    label: "Status",
    type: "selectStatus",
    placeholder: "",
    description: "Status",
  },
  {
    name: "sabespPerson",
    label: "Água pago por:",
    type: "selectFinancePerson",
    placeholder: "",
    description: "Status",
  },
  {
    name: "enel",
    label: "Luz",
    type: "date",
    placeholder: "",
    description: "",
  },
  {
    name: "enelValue",
    label: "Valor pago Luz",
    type: "price",
    placeholder: "",
    description: "",
  },
  {
    name: "statusEnel",
    label: "Status",
    type: "selectStatus",
    placeholder: "",
    description: "Status",
  },
  {
    name: "enelPerson",
    label: "Luz pago por:",
    type: "selectFinancePerson",
    placeholder: "",
    description: "Status",
  },
  {
    name: "gas",
    label: "Gás",
    type: "date",
    placeholder: "",
    description: "",
  },
  {
    name: "gasValue",
    label: "Valor pago Gás",
    type: "price",
    placeholder: "",
    description: "",
  },
  {
    name: "statusGas",
    label: "Status",
    type: "selectStatus",
    placeholder: "",
    description: "Status",
  },
  {
    name: "gasPerson",
    label: "Gás pago por:",
    type: "selectFinancePerson",
    placeholder: "",
    description: "Status",
  },
  {
    name: "extraValue",
    label: "Valor Extra",
    type: "price",
    placeholder: "",
    description: "",
  },
  {
    name: "extra",
    label: "Extra",
    type: "date",
    placeholder: "",
    description: "",
  },
  {
    name: "extraStatus",
    label: "Status",
    type: "selectStatus",
    placeholder: "",
    description: "Status",
  },
  {
    name: "extraPerson",
    label: "Extra pago por:",
    type: "selectFinancePerson",
    placeholder: "",
    description: "Pago por",
  },
  {
    name: "observations",
    label: "Observações",
    type: "text",
    placeholder: "",
    description: "",
  },
];
