"use client";
import { z } from "zod";

export const formSchema = z.object({
  status: z.string(),
  address: z.string(),
  paymentDay: z.string().optional(),
  paymentLocation: z.string().optional(),
  // rentalValue: z.number().optional(),
  numOfRooms: z.string().optional(),
  cleaningIncluded: z.boolean(),
  elevator: z.boolean(),
  garage: z.boolean().optional(),
  contractWith: z.string().optional(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  unoccupied: z.string().optional(),
  readjustmentIndex: z.string().optional(),
  administrator: z.string().optional(),
  admistratorPhoneNumber: z.string().optional(),
  admistratorEmail: z.string().optional(),
  administrateTax: z.string().optional(),
  lessee: z.string().optional(),
  lesseePhone: z.string().optional(),
  optionalContactName: z.string().optional(),
  optionalContactNumber: z.string().optional(),
  guarantor: z.string().optional(),
  guarnatorData: z.string().optional(),
  guarnatorNumber: z.string().optional(),
  condominium: z.number().optional(),
  IPTU: z.string().optional(),
  observation: z.string().optional(),
  nickname: z.string().min(3, "Deve ter no minimo 3 caracteres"),
  type: z.string().optional(),
  registration: z.string().optional(),
  scripture: z.string().optional(),
  registrationCertification: z.string().optional(),
  taxIPTU: z.number().optional(),
  rentValue: z.number().optional(),
  gas: z.number().optional(),
  light: z.number().optional(),
  water: z.number().optional(),
  lightInformation: z.string().optional(),
  waterInformation: z.string().optional(),
  contractRegistration: z.string().optional(),
  insurance: z.string().optional(),
  signatureRecognition: z.string().optional(),
  lawyer: z.string().optional(),
  lawyerData: z.string().optional(),
  beforePhoto: z.string().optional(),
  afterPhoto: z.string().optional(),
  proprietary: z.string().optional(),
});
